<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Achievement;

class AchievementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $achievements = [
            // === LIFESPAN ACHIEVEMENTS ===
            [
                'achievement_id' => 'born',
                'name' => 'A New Beginning',
                'description' => 'Start your life journey',
                'category' => 'lifespan',
                'rarity' => 'common',
                'icon' => 'mdi-baby-carriage',
                'conditions' => ['has_started' => true],
                'unlock_once' => true,
                'points' => 10,
            ],
            [
                'achievement_id' => 'childhood_complete',
                'name' => 'Growing Up',
                'description' => 'Complete your childhood (reach age 10)',
                'category' => 'lifespan',
                'rarity' => 'common',
                'icon' => 'mdi-child-care',
                'conditions' => ['min_age' => 10],
                'unlock_once' => true,
                'points' => 20,
            ],
            [
                'achievement_id' => 'teenager',
                'name' => 'Rebel Without a Cause',
                'description' => 'Become a teenager (reach age 13)',
                'category' => 'lifespan',
                'rarity' => 'common',
                'icon' => 'mdi-account-school',
                'conditions' => ['age_group' => 'teenager'],
                'unlock_once' => true,
                'points' => 25,
            ],
            [
                'achievement_id' => 'adult',
                'name' => 'Adulthood Begins',
                'description' => 'Become an adult (reach age 18)',
                'category' => 'lifespan',
                'rarity' => 'uncommon',
                'icon' => 'mdi-account-star',
                'conditions' => ['age_group' => 'adult'],
                'unlock_once' => true,
                'points' => 30,
            ],
            [
                'achievement_id' => 'middle_age',
                'name' => 'Mid-Life Crisis?',
                'description' => 'Reach age 35 - middle age begins',
                'category' => 'lifespan',
                'rarity' => 'rare',
                'icon' => 'mdi-account-clock',
                'conditions' => ['min_age' => 35],
                'unlock_once' => true,
                'points' => 40,
            ],
            [
                'achievement_id' => 'golden_years',
                'name' => 'Golden Years',
                'description' => 'Reach age 60 - retirement age',
                'category' => 'lifespan',
                'rarity' => 'epic',
                'icon' => 'mdi-palm-tree',
                'conditions' => ['age_group' => 'old'],
                'unlock_once' => true,
                'points' => 50,
            ],
            [
                'achievement_id' => 'century_life',
                'name' => 'Century Life',
                'description' => 'Live to age 100',
                'category' => 'lifespan',
                'rarity' => 'legendary',
                'icon' => 'mdi-crown',
                'conditions' => ['min_age' => 100],
                'unlock_once' => true,
                'points' => 100,
            ],

            // === CAREER ACHIEVEMENTS ===
            [
                'achievement_id' => 'first_job',
                'name' => 'Career Beginnings',
                'description' => 'Start your professional journey',
                'category' => 'career',
                'rarity' => 'common',
                'icon' => 'mdi-briefcase-outline',
                'conditions' => ['has_profession' => true],
                'unlock_once' => true,
                'points' => 25,
            ],
            [
                'achievement_id' => 'career_promotion',
                'name' => 'Moving Up',
                'description' => 'Get your first promotion',
                'category' => 'career',
                'rarity' => 'common',
                'icon' => 'mdi-arrow-up-bold',
                'conditions' => ['has_promotion' => true],
                'unlock_once' => true,
                'points' => 30,
            ],
            [
                'achievement_id' => 'senior_employee',
                'name' => 'Senior Employee',
                'description' => 'Reach senior level in your career',
                'category' => 'career',
                'rarity' => 'uncommon',
                'icon' => 'mdi-account-tie',
                'conditions' => ['career_level' => 'senior'],
                'unlock_once' => true,
                'points' => 40,
            ],
            [
                'achievement_id' => 'manager',
                'name' => 'The Boss',
                'description' => 'Become a manager',
                'category' => 'career',
                'rarity' => 'rare',
                'icon' => 'mdi-account-tie-hat',
                'conditions' => ['career_level' => 'manager'],
                'unlock_once' => true,
                'points' => 50,
            ],
            [
                'achievement_id' => 'executive',
                'name' => 'Executive',
                'description' => 'Reach executive level - the top!',
                'category' => 'career',
                'rarity' => 'epic',
                'icon' => 'mdi-star',
                'conditions' => ['career_level' => 'executive'],
                'unlock_once' => true,
                'points' => 75,
            ],
            [
                'achievement_id' => 'retired',
                'name' => 'Retirement',
                'description' => 'Retire from your career',
                'category' => 'career',
                'rarity' => 'rare',
                'icon' => 'mdi-palm-tree',
                'conditions' => ['career_level' => 'retired'],
                'unlock_once' => true,
                'points' => 40,
            ],
            [
                'achievement_id' => 'career_struggle',
                'name' => 'Career Struggle',
                'description' => 'Experience unemployment',
                'category' => 'career',
                'rarity' => 'uncommon',
                'icon' => 'mdi-account-off',
                'conditions' => ['was_unemployed' => true],
                'unlock_once' => true,
                'points' => 15,
            ],

            // === HEALTH ACHIEVEMENTS ===
            [
                'achievement_id' => 'perfect_health',
                'name' => 'Peak Health',
                'description' => 'Reach 100% health',
                'category' => 'health',
                'rarity' => 'uncommon',
                'icon' => 'mdi-heart',
                'conditions' => ['min_health' => 100],
                'unlock_once' => true,
                'points' => 35,
            ],
            [
                'achievement_id' => 'healthy_streak',
                'name' => 'Healthy Streak',
                'description' => 'Maintain 80%+ health for 10 years',
                'category' => 'health',
                'rarity' => 'rare',
                'icon' => 'mdi-heart-pulse',
                'conditions' => ['health_streak_years' => 10],
                'unlock_once' => true,
                'points' => 50,
            ],
            [
                'achievement_id' => 'survivor',
                'name' => 'Survivor',
                'description' => 'Recover from poor health',
                'category' => 'health',
                'rarity' => 'uncommon',
                'icon' => 'mdi-hospital-box',
                'conditions' => ['recovered_from_poor_health' => true],
                'unlock_once' => true,
                'points' => 40,
            ],
            [
                'achievement_id' => 'burnout',
                'name' => 'Burned Out',
                'description' => 'Experience career burnout',
                'category' => 'health',
                'rarity' => 'uncommon',
                'icon' => 'mdi-fire',
                'conditions' => ['had_burnout' => true],
                'unlock_once' => true,
                'points' => 20,
            ],
            [
                'achievement_id' => 'blissful',
                'name' => 'Blissful',
                'description' => 'Reach 100% happiness',
                'category' => 'health',
                'rarity' => 'uncommon',
                'icon' => 'mdi-emoticon',
                'conditions' => ['min_happiness' => 100],
                'unlock_once' => true,
                'points' => 35,
            ],
            [
                'achievement_id' => 'happy_streak',
                'name' => 'Joyful Life',
                'description' => 'Maintain 80%+ happiness for 10 years',
                'category' => 'health',
                'rarity' => 'rare',
                'icon' => 'mdi-emoticon-happy',
                'conditions' => ['happiness_streak_years' => 10],
                'unlock_once' => true,
                'points' => 50,
            ],
            [
                'achievement_id' => 'depressed',
                'name' => 'Dark Times',
                'description' => 'Experience very low happiness',
                'category' => 'health',
                'rarity' => 'uncommon',
                'icon' => 'mdi-emoticon-sad',
                'conditions' => ['had_low_happiness' => true],
                'unlock_once' => true,
                'points' => 20,
            ],

            // === RELATIONSHIP ACHIEVEMENTS ===
            [
                'achievement_id' => 'first_date',
                'name' => 'First Date',
                'description' => 'Go on your first date',
                'category' => 'relationship',
                'rarity' => 'common',
                'icon' => 'mdi-heart-outline',
                'conditions' => ['has_dated' => true],
                'unlock_once' => true,
                'points' => 25,
            ],
            [
                'achievement_id' => 'dating',
                'name' => 'In a Relationship',
                'description' => 'Enter a relationship',
                'category' => 'relationship',
                'rarity' => 'uncommon',
                'icon' => 'mdi-heart-multiple',
                'conditions' => ['relationship_status' => 'dating'],
                'unlock_once' => true,
                'points' => 30,
            ],
            [
                'achievement_id' => 'engaged',
                'name' => 'Engaged',
                'description' => 'Get engaged',
                'category' => 'relationship',
                'rarity' => 'rare',
                'icon' => 'mdi-ring',
                'conditions' => ['relationship_status' => 'engaged'],
                'unlock_once' => true,
                'points' => 45,
            ],
            [
                'achievement_id' => 'married',
                'name' => 'Marriage',
                'description' => 'Get married',
                'category' => 'relationship',
                'rarity' => 'rare',
                'icon' => 'mdi-heart',
                'conditions' => ['relationship_status' => 'married'],
                'unlock_once' => true,
                'points' => 50,
            ],
            [
                'achievement_id' => 'divorced',
                'name' => 'New Beginnings',
                'description' => 'Experience divorce',
                'category' => 'relationship',
                'rarity' => 'uncommon',
                'icon' => 'mdi-heart-broken',
                'conditions' => ['relationship_status' => 'divorced'],
                'unlock_once' => true,
                'points' => 25,
            ],

            // === SKILLS ACHIEVEMENTS ===
            [
                'achievement_id' => 'first_skill',
                'name' => 'Apprentice',
                'description' => 'Learn your first skill',
                'category' => 'skills',
                'rarity' => 'common',
                'icon' => 'mdi-school',
                'conditions' => ['skills_count' => 1],
                'unlock_once' => true,
                'points' => 20,
            ],
            [
                'achievement_id' => 'skilled',
                'name' => 'Multi-Skilled',
                'description' => 'Learn 5 different skills',
                'category' => 'skills',
                'rarity' => 'uncommon',
                'icon' => 'mdi-star-outline',
                'conditions' => ['skills_count' => 5],
                'unlock_once' => true,
                'points' => 35,
            ],
            [
                'achievement_id' => 'master',
                'name' => 'Master',
                'description' => 'Learn 10 different skills',
                'category' => 'skills',
                'rarity' => 'rare',
                'icon' => 'mdi-star-half-full',
                'conditions' => ['skills_count' => 10],
                'unlock_once' => true,
                'points' => 50,
            ],

            // === SOCIAL ACHIEVEMENTS ===
            [
                'achievement_id' => 'first_friend',
                'name' => 'Social Butterfly',
                'description' => 'Make your first social connection',
                'category' => 'social',
                'rarity' => 'common',
                'icon' => 'mdi-account-group',
                'conditions' => ['social_connections_count' => 1],
                'unlock_once' => true,
                'points' => 15,
            ],
            [
                'achievement_id' => 'popular',
                'name' => 'Popular',
                'description' => 'Have 5 social connections',
                'category' => 'social',
                'rarity' => 'uncommon',
                'icon' => 'mdi-account-group',
                'conditions' => ['social_connections_count' => 5],
                'unlock_once' => true,
                'points' => 30,
            ],
            [
                'achievement_id' => 'influencer',
                'name' => 'Influencer',
                'description' => 'Have 10 social connections',
                'category' => 'social',
                'rarity' => 'rare',
                'icon' => 'mdi-crown',
                'conditions' => ['social_connections_count' => 10],
                'unlock_once' => true,
                'points' => 45,
            ],

            // === DECISIONS ACHIEVEMENTS ===
            [
                'achievement_id' => 'first_choice',
                'name' => 'Decision Maker',
                'description' => 'Make your first major life decision',
                'category' => 'milestone',
                'rarity' => 'common',
                'icon' => 'mdi-cursor-default-click',
                'conditions' => ['total_decisions' => 1],
                'unlock_once' => true,
                'points' => 10,
            ],
            [
                'achievement_id' => 'decades_of_decisions',
                'name' => 'Decades of Decisions',
                'description' => 'Make 50 major life decisions',
                'category' => 'milestone',
                'rarity' => 'rare',
                'icon' => 'mdi-decagram',
                'conditions' => ['total_decisions' => 50],
                'unlock_once' => true,
                'points' => 60,
            ],

            // === LUCK ACHIEVEMENTS ===
            [
                'achievement_id' => 'lucky',
                'name' => 'Lucky',
                'description' => 'Have luck stat reach 80+',
                'category' => 'luck',
                'rarity' => 'uncommon',
                'icon' => 'mdi-clover',
                'conditions' => ['min_luck' => 80],
                'unlock_once' => true,
                'points' => 40,
            ],
            [
                'achievement_id' => 'unlucky',
                'name' => 'Unlucky',
                'description' => 'Have luck stat drop to 20 or below',
                'category' => 'luck',
                'rarity' => 'uncommon',
                'icon' => 'mdi-cloud-off',
                'conditions' => ['max_luck' => 20],
                'unlock_once' => true,
                'points' => 20,
            ],
            [
                'achievement_id' => 'balanced_karma',
                'name' => 'Balanced Karma',
                'description' => 'Have karma between 40 and 60',
                'category' => 'luck',
                'rarity' => 'common',
                'icon' => 'mdi-scale-balance',
                'conditions' => ['karma_range' => [40, 60]],
                'unlock_once' => true,
                'points' => 25,
            ],

            // === SPECIAL ACHIEVEMENTS ===
            [
                'achievement_id' => 'comeback_kid',
                'name' => 'Comeback Kid',
                'description' => 'Recover from very low stats to good stats',
                'category' => 'special',
                'rarity' => 'rare',
                'icon' => 'mdi-arrow-up-bold-circle',
                'conditions' => ['made_comback' => true],
                'unlock_once' => true,
                'points' => 55,
            ],
            [
                'achievement_id' => 'extremist',
                'name' => 'Extremist',
                'description' => 'Experience both very high and very low stats',
                'category' => 'special',
                'rarity' => 'epic',
                'icon' => 'mdi-chart-timeline-variant',
                'conditions' => ['had_extreme_stats' => true],
                'unlock_once' => true,
                'points' => 60,
            ],
            [
                'achievement_id' => 'maxed_out',
                'name' => 'Maxed Out',
                'description' => 'Reach 100 in any stat',
                'category' => 'special',
                'rarity' => 'epic',
                'icon' => 'mdi-trophy',
                'conditions' => ['maxed_stat' => true],
                'unlock_once' => true,
                'points' => 70,
            ],
        ];

        foreach ($achievements as $achievement) {
            Achievement::updateOrCreate(
                ['achievement_id' => $achievement['achievement_id']],
                $achievement
            );
        }

        $this->command->info('Achievements seeded successfully!');
    }
}
