<?php
namespace Database\Seeders;
use App\Models\ProfessionPathEvent;
use Database\Seeders\Concerns\GeneratesOutcomeChoices;
use Illuminate\Database\Seeder;
class ProfessionPathEventSeeder extends Seeder
{
    use GeneratesOutcomeChoices;
    /**
     * Run the database seeds.
     * 
     * Profession path events with choices structure:
     * - type: 'profession'
     * - deck_label: 'Profession Event'
     * - Each event has: title, description, image, type, deck_label, repeatable, weight, 
     *   auto_resolve, days_to_advance, display_order, choices, conditions, profession
     */
    public function run(): void
    {
        $events = [
            // Doctor Profession Events
            [
                'profession' => 'Doctor',
                'title' => 'Emergency Surgery',
                'description' => 'A critical patient needs emergency surgery. Your skills are needed.',
                'image' => '/css/images/profession/doctor.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Perform surgery', 'stat_effects' => '+15 Morality, +10 Reputation, +5 Happiness', 'days_to_advance' => 0],
                    ['text' => 'Decline', 'stat_effects' => '-5 Morality, -3 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Doctor'],
            ],
            [
                'profession' => 'Doctor',
                'title' => 'Medical Error',
                'description' => 'A medical error occurred during treatment. The patient\'s family is upset.',
                'image' => '/css/images/profession/doctor.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Apologize and compensate', 'stat_effects' => '-10 Wealth, -5 Reputation, +5 Morality', 'days_to_advance' => 0],
                    ['text' => 'Deny responsibility', 'stat_effects' => '-15 Reputation, +5 Ego, -10 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Doctor'],
            ],
            [
                'profession' => 'Doctor',
                'title' => 'Award Ceremony',
                'description' => 'You are recognized for your contributions to medicine.',
                'image' => '/css/images/profession/doctor.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Accept award', 'stat_effects' => '+20 Reputation, +10 Ego', 'days_to_advance' => 0],
                    ['text' => 'Decline', 'stat_effects' => '+5 Morality, -5 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Doctor'],
            ],
            [
                'profession' => 'Doctor',
                'title' => 'Research Grant',
                'description' => 'You receive a research grant for medical studies.',
                'image' => '/css/images/profession/doctor.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 4,
                'choices' => [
                    ['text' => 'Accept grant', 'stat_effects' => '+15 Wealth, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Decline', 'stat_effects' => '+5 Discipline, -5 Wealth', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Doctor'],
            ],
            [
                'profession' => 'Doctor',
                'title' => 'Breakthrough Discovery',
                'description' => 'You make a major medical breakthrough!',
                'image' => '/css/images/profession/doctor.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 1,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 5,
                'choices' => [
                    ['text' => 'Publish discovery', 'stat_effects' => '+20 Reputation, +15 Ego, +10 Wealth', 'days_to_advance' => 0],
                    ['text' => 'Keep secret', 'stat_effects' => '+10 Ego, -10 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Doctor'],
            ],
            // Teacher Profession Events
            [
                'profession' => 'Teacher',
                'title' => 'Inspiring Lecture',
                'description' => 'You deliver an inspiring lecture that moves students.',
                'image' => '/css/images/profession/teacher.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Continue inspiring', 'stat_effects' => '+10 Reputation, +5 Happiness', 'days_to_advance' => 0],
                    ['text' => 'Return to normal', 'stat_effects' => '+3 Discipline, -2 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Teacher'],
            ],
            [
                'profession' => 'Teacher',
                'title' => 'Classroom Chaos',
                'description' => 'The classroom becomes unmanageable.',
                'image' => '/css/images/profession/teacher.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Take control', 'stat_effects' => '+5 Discipline, -2 Happiness', 'days_to_advance' => 0],
                    ['text' => 'Ignore it', 'stat_effects' => '-5 Discipline, -5 Happiness', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Teacher'],
            ],
            [
                'profession' => 'Teacher',
                'title' => 'Student Success',
                'description' => 'Your student achieves great success thanks to your guidance.',
                'image' => '/css/images/profession/teacher.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Celebrate success', 'stat_effects' => '+15 Reputation, +10 Happiness', 'days_to_advance' => 0],
                    ['text' => 'Stay modest', 'stat_effects' => '+5 Morality, +3 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Teacher'],
            ],
            [
                'profession' => 'Teacher',
                'title' => 'School Award',
                'description' => 'You receive an award for excellence in teaching.',
                'image' => '/css/images/profession/teacher.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 4,
                'choices' => [
                    ['text' => 'Accept award', 'stat_effects' => '+15 Reputation, +10 Ego', 'days_to_advance' => 0],
                    ['text' => 'Decline', 'stat_effects' => '+5 Morality, -3 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Teacher'],
            ],
            // Scientist Profession Events
            [
                'profession' => 'Scientist',
                'title' => 'Breakthrough Discovery',
                'description' => 'You make a major scientific breakthrough!',
                'image' => '/css/images/profession/scientist.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Publish findings', 'stat_effects' => '+20 Reputation, +15 Ego, +10 Wealth', 'days_to_advance' => 0],
                    ['text' => 'Keep secret', 'stat_effects' => '+10 Ego, -10 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Scientist'],
            ],
            [
                'profession' => 'Scientist',
                'title' => 'Failed Experiment',
                'description' => 'Your experiment fails spectacularly.',
                'image' => '/css/images/profession/scientist.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Try again', 'stat_effects' => '+5 Discipline, -2 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Give up', 'stat_effects' => '-5 Reputation, +5 Burnout', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Scientist'],
            ],
            [
                'profession' => 'Scientist',
                'title' => 'Research Grant',
                'description' => 'You receive funding for your research.',
                'image' => '/css/images/profession/scientist.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Accept grant', 'stat_effects' => '+15 Wealth, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Decline', 'stat_effects' => '+5 Discipline, -5 Wealth', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Scientist'],
            ],
            // Engineer Profession Events
            [
                'profession' => 'Engineer',
                'title' => 'Project Launch',
                'description' => 'A major engineering project is ready to launch.',
                'image' => '/css/images/profession/engineer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Launch project', 'stat_effects' => '+15 Reputation, +10 Wealth', 'days_to_advance' => 0],
                    ['text' => 'Delay launch', 'stat_effects' => '-5 Wealth, +3 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Engineer'],
            ],
            [
                'profession' => 'Engineer',
                'title' => 'Design Flaw',
                'description' => 'A design flaw is discovered in your project.',
                'image' => '/css/images/profession/engineer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Fix immediately', 'stat_effects' => '-10 Wealth, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Ignore it', 'stat_effects' => '+5 Wealth, -15 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Engineer'],
            ],
            [
                'profession' => 'Engineer',
                'title' => 'Innovation Award',
                'description' => 'You receive an award for your innovative design.',
                'image' => '/css/images/profession/engineer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Accept award', 'stat_effects' => '+20 Reputation, +10 Ego', 'days_to_advance' => 0],
                    ['text' => 'Share credit', 'stat_effects' => '+10 Reputation, +5 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Engineer'],
            ],

            // Nurse Profession Events
            [
                'profession' => 'Nurse',
                'title' => 'Patient Care',
                'description' => 'A patient requires intensive care.',
                'image' => '/css/images/profession/nurse.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Provide extra care', 'stat_effects' => '+15 Morality, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Follow routine', 'stat_effects' => '+3 Morality, +3 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Nurse'],
            ],
            [
                'profession' => 'Nurse',
                'title' => 'Hospital Crisis',
                'description' => 'The hospital faces a staffing crisis.',
                'image' => '/css/images/profession/nurse.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Work overtime', 'stat_effects' => '+10 Morality, -10 Happiness, +5 Burnout', 'days_to_advance' => 0],
                    ['text' => 'Refuse extra hours', 'stat_effects' => '+5 Happiness, -5 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Nurse'],
            ],
            [
                'profession' => 'Nurse',
                'title' => 'Thankful Patient',
                'description' => 'A patient expresses gratitude for your care.',
                'image' => '/css/images/profession/nurse.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Accept thanks', 'stat_effects' => '+10 Happiness, +5 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Stay humble', 'stat_effects' => '+5 Morality, +3 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Nurse'],
            ],

            // Soldier Profession Events
            [
                'profession' => 'Soldier',
                'title' => 'Combat Mission',
                'description' => 'You are assigned a dangerous combat mission.',
                'image' => '/css/images/profession/soldier.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Complete mission', 'stat_effects' => '+20 Reputation, +10 Morality', 'days_to_advance' => 0],
                    ['text' => 'Play it safe', 'stat_effects' => '+5 Reputation, +3 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Soldier'],
            ],
            [
                'profession' => 'Soldier',
                'title' => 'Deployment',
                'description' => 'You receive deployment orders.',
                'image' => '/css/images/profession/soldier.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Accept deployment', 'stat_effects' => '+10 Morality, -10 Happiness', 'days_to_advance' => 0],
                    ['text' => 'Request exemption', 'stat_effects' => '+5 Happiness, -10 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Soldier'],
            ],
            [
                'profession' => 'Soldier',
                'title' => 'Military Award',
                'description' => 'You receive a medal for your service.',
                'image' => '/css/images/profession/soldier.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Accept medal', 'stat_effects' => '+20 Reputation, +10 Ego', 'days_to_advance' => 0],
                    ['text' => 'Decline', 'stat_effects' => '+5 Morality, -5 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Soldier'],
            ],

            // Athlete Profession Events
            [
                'profession' => 'Athlete',
                'title' => 'Championship',
                'description' => 'You qualify for a major championship.',
                'image' => '/css/images/profession/athlete.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Win championship', 'stat_effects' => '+20 Reputation, +15 Wealth', 'days_to_advance' => 0],
                    ['text' => 'Participate', 'stat_effects' => '+5 Reputation, +3 Wealth', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Athlete'],
            ],
            [
                'profession' => 'Athlete',
                'title' => 'Injury',
                'description' => 'You sustain a serious injury.',
                'image' => '/css/images/profession/athlete.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Recover fully', 'stat_effects' => '+10 Health, +5 Discipline', 'days_to_advance' => 0],
                    ['text' => 'Rush back', 'stat_effects' => '-10 Health, +5 Ego', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Athlete'],
            ],
            [
                'profession' => 'Athlete',
                'title' => 'Endorsement',
                'description' => 'A brand offers you an endorsement deal.',
                'image' => '/css/images/profession/athlete.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Accept deal', 'stat_effects' => '+15 Wealth, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Decline', 'stat_effects' => '+5 Morality, +3 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Athlete'],
            ],

            // Fisher Profession Events
            [
                'profession' => 'Fisher',
                'title' => 'Big Catch',
                'description' => 'You catch a huge fish!',
                'image' => '/css/images/profession/fisher.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Sell catch', 'stat_effects' => '+15 Wealth, +5 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Keep catch', 'stat_effects' => '+10 Happiness, +3 Health', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Fisher'],
            ],
            [
                'profession' => 'Fisher',
                'title' => 'Storm at Sea',
                'description' => 'A storm catches you at sea.',
                'image' => '/css/images/profession/fisher.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Fight storm', 'stat_effects' => '+10 Strength, +5 Discipline', 'days_to_advance' => 0],
                    ['text' => 'Return to shore', 'stat_effects' => '-5 Wealth, +5 Happiness', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Fisher'],
            ],
            [
                'profession' => 'Fisher',
                'title' => 'New Boat',
                'description' => 'You can afford a new boat.',
                'image' => '/css/images/profession/fisher.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Buy boat', 'stat_effects' => '-20 Wealth, +15 Wealth', 'days_to_advance' => 0],
                    ['text' => 'Keep old boat', 'stat_effects' => '+5 Wealth, +3 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Fisher'],
            ],

            // Artist Profession Events
            [
                'profession' => 'Artist',
                'title' => 'Art Exhibition',
                'description' => 'Your artwork is featured in an exhibition.',
                'image' => '/css/images/profession/artist.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Showcase art', 'stat_effects' => '+20 Reputation, +10 Creativity', 'days_to_advance' => 0],
                    ['text' => 'Skip exhibition', 'stat_effects' => '+5 Creativity, -5 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Artist'],
            ],
            [
                'profession' => 'Artist',
                'title' => 'Creative Block',
                'description' => 'You experience creative block.',
                'image' => '/css/images/profession/artist.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Push through', 'stat_effects' => '+10 Creativity, +5 Discipline', 'days_to_advance' => 0],
                    ['text' => 'Take break', 'stat_effects' => '+10 Happiness, -5 Creativity', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Artist'],
            ],
            [
                'profession' => 'Artist',
                'title' => 'Art Sale',
                'description' => 'Someone wants to buy your artwork.',
                'image' => '/css/images/profession/artist.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Sell artwork', 'stat_effects' => '+15 Wealth, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Keep artwork', 'stat_effects' => '+10 Creativity, +5 Happiness', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Artist'],
            ],

            // Writer Profession Events
            [
                'profession' => 'Writer',
                'title' => 'Book Publication',
                'description' => 'Your book is ready for publication.',
                'image' => '/css/images/profession/writer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Publish book', 'stat_effects' => '+20 Reputation, +10 Wealth', 'days_to_advance' => 0],
                    ['text' => 'Self-publish', 'stat_effects' => '+10 Reputation, +5 Creativity', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Writer'],
            ],
            [
                'profession' => 'Writer',
                'title' => 'Writer\'s Block',
                'description' => 'You face writer\'s block.',
                'image' => '/css/images/profession/writer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Power through', 'stat_effects' => '+10 Creativity, +5 Discipline', 'days_to_advance' => 0],
                    ['text' => 'Take vacation', 'stat_effects' => '+10 Happiness, -5 Creativity', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Writer'],
            ],
            [
                'profession' => 'Writer',
                'title' => 'Award Nomination',
                'description' => 'Your work is nominated for an award.',
                'image' => '/css/images/profession/writer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Win award', 'stat_effects' => '+25 Reputation, +10 Ego', 'days_to_advance' => 0],
                    ['text' => 'Attend ceremony', 'stat_effects' => '+10 Reputation, +5 Happiness', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Writer'],
            ],

            // Designer Profession Events
            [
                'profession' => 'Designer',
                'title' => 'Design Project',
                'description' => 'You receive a major design project.',
                'image' => '/css/images/profession/designer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Complete project', 'stat_effects' => '+15 Reputation, +10 Wealth', 'days_to_advance' => 0],
                    ['text' => 'Delay project', 'stat_effects' => '-5 Reputation, +3 Creativity', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Designer'],
            ],
            [
                'profession' => 'Designer',
                'title' => 'Client Feedback',
                'description' => 'A client gives you feedback on your design.',
                'image' => '/css/images/profession/designer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Incorporate feedback', 'stat_effects' => '+10 Reputation, +5 Discipline', 'days_to_advance' => 0],
                    ['text' => 'Defend design', 'stat_effects' => '+5 Creativity, -5 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Designer'],
            ],
            [
                'profession' => 'Designer',
                'title' => 'Portfolio Review',
                'description' => 'Your portfolio gets reviewed by experts.',
                'image' => '/css/images/profession/designer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Positive review', 'stat_effects' => '+15 Reputation, +10 Creativity', 'days_to_advance' => 0],
                    ['text' => 'Critical review', 'stat_effects' => '-5 Reputation, +5 Creativity', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Designer'],
            ],

            // Chef Profession Events
            [
                'profession' => 'Chef',
                'title' => 'Restaurant Review',
                'description' => 'A famous food critic reviews your restaurant.',
                'image' => '/css/images/profession/chef.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Great review', 'stat_effects' => '+20 Reputation, +15 Wealth', 'days_to_advance' => 0],
                    ['text' => 'Bad review', 'stat_effects' => '-10 Reputation, +5 Creativity', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Chef'],
            ],
            [
                'profession' => 'Chef',
                'title' => 'Menu Innovation',
                'description' => 'You create a new dish.',
                'image' => '/css/images/profession/chef.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Add to menu', 'stat_effects' => '+10 Creativity, +5 Wealth', 'days_to_advance' => 0],
                    ['text' => 'Keep secret', 'stat_effects' => '+5 Creativity, +5 Happiness', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Chef'],
            ],
            [
                'profession' => 'Chef',
                'title' => 'Kitchen Disaster',
                'description' => 'A disaster happens in the kitchen.',
                'image' => '/css/images/profession/chef.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Fix quickly', 'stat_effects' => '-5 Wealth, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Close kitchen', 'stat_effects' => '-10 Wealth, +5 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Chef'],
            ],

            // Actor Profession Events
            [
                'profession' => 'Actor',
                'title' => 'Audition',
                'description' => 'You audition for a major film role.',
                'image' => '/css/images/profession/actor.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Get role', 'stat_effects' => '+20 Reputation, +15 Wealth', 'days_to_advance' => 0],
                    ['text' => 'Lose role', 'stat_effects' => '+5 Creativity, +3 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Actor'],
            ],
            [
                'profession' => 'Actor',
                'title' => 'Film Premiere',
                'description' => 'Your film has a premiere.',
                'image' => '/css/images/profession/actor.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Attend premiere', 'stat_effects' => '+15 Reputation, +10 Ego', 'days_to_advance' => 0],
                    ['text' => 'Skip premiere', 'stat_effects' => '+5 Happiness, -5 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Actor'],
            ],
            [
                'profession' => 'Actor',
                'title' => 'Scandal',
                'description' => 'A scandal involving you emerges.',
                'image' => '/css/images/profession/actor.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Address scandal', 'stat_effects' => '-10 Reputation, +5 Morality', 'days_to_advance' => 0],
                    ['text' => 'Ignore it', 'stat_effects' => '-15 Reputation, +5 Ego', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Actor'],
            ],

            // Journalist Profession Events
            [
                'profession' => 'Journalist',
                'title' => 'Breaking News',
                'description' => 'You discover a breaking news story.',
                'image' => '/css/images/profession/journalist.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Publish story', 'stat_effects' => '+20 Reputation, +10 Wealth', 'days_to_advance' => 0],
                    ['text' => 'Sit on story', 'stat_effects' => '-10 Reputation, +5 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Journalist'],
            ],
            [
                'profession' => 'Journalist',
                'title' => 'Interview',
                'description' => 'You interview an important person.',
                'image' => '/css/images/profession/journalist.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Great interview', 'stat_effects' => '+15 Reputation, +10 Creativity', 'days_to_advance' => 0],
                    ['text' => 'Awkward interview', 'stat_effects' => '-5 Reputation, +5 Creativity', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Journalist'],
            ],
            [
                'profession' => 'Journalist',
                'title' => 'Plagiarism Accusation',
                'description' => 'You are accused of plagiarism.',
                'image' => '/css/images/profession/journalist.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Defend yourself', 'stat_effects' => '-10 Reputation, +10 Discipline', 'days_to_advance' => 0],
                    ['text' => 'Apologize', 'stat_effects' => '-15 Reputation, +5 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Journalist'],
            ],

            // Business Owner Profession Events
            [
                'profession' => 'Business Owner',
                'title' => 'Business Expansion',
                'description' => 'You consider expanding your business.',
                'image' => '/css/images/profession/entrepreneur.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Expand business', 'stat_effects' => '+25 Wealth, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Stay small', 'stat_effects' => '+5 Wealth, +5 Happiness', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Business Owner'],
            ],
            [
                'profession' => 'Business Owner',
                'title' => 'Competitor',
                'description' => 'A new competitor enters the market.',
                'image' => '/css/images/profession/entrepreneur.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Compete aggressively', 'stat_effects' => '-10 Wealth, +15 Discipline', 'days_to_advance' => 0],
                    ['text' => 'Differentiate', 'stat_effects' => '+10 Reputation, +5 Creativity', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Business Owner'],
            ],
            [
                'profession' => 'Business Owner',
                'title' => 'Employee Issue',
                'description' => 'An employee causes a problem.',
                'image' => '/css/images/profession/entrepreneur.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Fire employee', 'stat_effects' => '-5 Morality, +10 Discipline', 'days_to_advance' => 0],
                    ['text' => 'Give warning', 'stat_effects' => '+5 Morality, -5 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Business Owner'],
            ],

            // Investor Profession Events
            [
                'profession' => 'Investor',
                'title' => 'Investment Opportunity',
                'description' => 'A new investment opportunity arises.',
                'image' => '/css/images/profession/investor.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Invest', 'stat_effects' => '+20 Wealth, +10 Luck', 'days_to_advance' => 0],
                    ['text' => 'Pass', 'stat_effects' => '+5 Wealth, +3 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Investor'],
            ],
            [
                'profession' => 'Investor',
                'title' => 'Market Crash',
                'description' => 'The market crashes suddenly.',
                'image' => '/css/images/profession/investor.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Sell holdings', 'stat_effects' => '-15 Wealth, +5 Discipline', 'days_to_advance' => 0],
                    ['text' => 'Hold', 'stat_effects' => '-10 Wealth, +10 Luck', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Investor'],
            ],
            [
                'profession' => 'Investor',
                'title' => 'Successful Exit',
                'description' => 'One of your investments pays off big.',
                'image' => '/css/images/profession/investor.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Celebrate', 'stat_effects' => '+25 Wealth, +10 Ego', 'days_to_advance' => 0],
                    ['text' => 'Reinvest', 'stat_effects' => '+15 Wealth, +5 Reputation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Investor'],
            ],

            // Politician Profession Events
            [
                'profession' => 'Politician',
                'title' => 'Election',
                'description' => 'You run for political office.',
                'image' => '/css/images/profession/politician.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Win election', 'stat_effects' => '+25 Reputation, +15 Ego', 'days_to_advance' => 0],
                    ['text' => 'Lose election', 'stat_effects' => '-10 Reputation, +5 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Politician'],
            ],
            [
                'profession' => 'Politician',
                'title' => 'Scandal',
                'description' => 'A political scandal emerges.',
                'image' => '/css/images/profession/politician.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Address scandal', 'stat_effects' => '-15 Reputation, +10 Morality', 'days_to_advance' => 0],
                    ['text' => 'Deny everything', 'stat_effects' => '-20 Reputation, +5 Ego', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Politician'],
            ],
            [
                'profession' => 'Politician',
                'title' => 'Policy Win',
                'description' => 'Your policy gets passed.',
                'image' => '/css/images/profession/politician.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Celebrate win', 'stat_effects' => '+20 Reputation, +10 Ego', 'days_to_advance' => 0],
                    ['text' => 'Stay humble', 'stat_effects' => '+10 Reputation, +5 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Politician'],
            ],

            // Performer Profession Events
            [
                'profession' => 'Performer',
                'title' => 'Performance',
                'description' => 'You give a live performance.',
                'image' => '/css/images/profession/musician.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Great show', 'stat_effects' => '+20 Reputation, +15 Happiness', 'days_to_advance' => 0],
                    ['text' => 'Poor show', 'stat_effects' => '-5 Reputation, +5 Creativity', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Performer'],
            ],
            [
                'profession' => 'Performer',
                'title' => 'Fan Encounter',
                'description' => 'A fan approaches you.',
                'image' => '/css/images/profession/musician.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Meet fan', 'stat_effects' => '+10 Reputation, +10 Happiness', 'days_to_advance' => 0],
                    ['text' => 'Ignore fan', 'stat_effects' => '-5 Reputation, +5 Ego', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Performer'],
            ],
            [
                'profession' => 'Performer',
                'title' => 'Career Milestone',
                'description' => 'You reach a career milestone.',
                'image' => '/css/images/profession/musician.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Celebrate', 'stat_effects' => '+15 Reputation, +10 Ego', 'days_to_advance' => 0],
                    ['text' => 'Reflect', 'stat_effects' => '+10 Happiness, +5 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Performer'],
            ],

            // Salesperson Profession Events
            [
                'profession' => 'Salesperson',
                'title' => 'Big Sale',
                'description' => 'You close a major sale.',
                'image' => '/css/images/profession/realestate.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Close deal', 'stat_effects' => '+20 Wealth, +15 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Negotiate more', 'stat_effects' => '+10 Wealth, +5 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Salesperson'],
            ],
            [
                'profession' => 'Salesperson',
                'title' => 'Rejection',
                'description' => 'You face a major rejection.',
                'image' => '/css/images/profession/realestate.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Move on', 'stat_effects' => '+10 Discipline, +5 Happiness', 'days_to_advance' => 0],
                    ['text' => 'Get discouraged', 'stat_effects' => '-10 Happiness, -5 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Salesperson'],
            ],
            [
                'profession' => 'Salesperson',
                'title' => 'Promotion',
                'description' => 'You get promoted.',
                'image' => '/css/images/profession/realestate.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Accept promotion', 'stat_effects' => '+15 Wealth, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Decline', 'stat_effects' => '+5 Happiness, +3 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Salesperson'],
            ],

            // Community Leader Profession Events
            [
                'profession' => 'Community Leader',
                'title' => 'Community Project',
                'description' => 'You lead a community project.',
                'image' => '/css/images/profession/community.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Lead project', 'stat_effects' => '+20 Reputation, +15 Morality', 'days_to_advance' => 0],
                    ['text' => 'Delegate', 'stat_effects' => '+10 Reputation, +5 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Community Leader'],
            ],
            [
                'profession' => 'Community Leader',
                'title' => 'Conflict Resolution',
                'description' => 'A conflict arises in the community.',
                'image' => '/css/images/profession/community.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Mediate', 'stat_effects' => '+15 Reputation, +10 Morality', 'days_to_advance' => 0],
                    ['text' => 'Avoid conflict', 'stat_effects' => '-5 Reputation, +5 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Community Leader'],
            ],
            [
                'profession' => 'Community Leader',
                'title' => 'Award',
                'description' => 'You receive a community award.',
                'image' => '/css/images/profession/community.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Accept award', 'stat_effects' => '+20 Reputation, +10 Ego', 'days_to_advance' => 0],
                    ['text' => 'Share credit', 'stat_effects' => '+15 Reputation, +10 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Community Leader'],
            ],

            // Philosopher/Poet Profession Events
            [
                'profession' => 'Philosopher/Poet',
                'title' => 'Philosophy Publication',
                'description' => 'You publish a philosophical work.',
                'image' => '/css/images/profession/philosopher.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Publish work', 'stat_effects' => '+20 Reputation, +15 Creativity', 'days_to_advance' => 0],
                    ['text' => 'Keep private', 'stat_effects' => '+10 Creativity, +5 Isolation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Philosopher/Poet'],
            ],
            [
                'profession' => 'Philosopher/Poet',
                'title' => 'Debate',
                'description' => 'You engage in a public debate.',
                'image' => '/css/images/profession/philosopher.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Win debate', 'stat_effects' => '+20 Reputation, +10 Intelligence', 'days_to_advance' => 0],
                    ['text' => 'Lose debate', 'stat_effects' => '-5 Reputation, +5 Creativity', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Philosopher/Poet'],
            ],
            [
                'profession' => 'Philosopher/Poet',
                'title' => 'Inspiration',
                'description' => 'You experience a moment of inspiration.',
                'image' => '/css/images/profession/philosopher.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Create work', 'stat_effects' => '+15 Creativity, +10 Intelligence', 'days_to_advance' => 0],
                    ['text' => 'Meditate', 'stat_effects' => '+10 Happiness, +5 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Philosopher/Poet'],
            ],

            // Gambler Profession Events
            [
                'profession' => 'Gambler',
                'title' => 'Big Bet',
                'description' => 'You place a big bet.',
                'image' => '/css/images/profession/gambler.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Win bet', 'stat_effects' => '+30 Wealth, +15 Luck', 'days_to_advance' => 0],
                    ['text' => 'Lose bet', 'stat_effects' => '-20 Wealth, +5 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Gambler'],
            ],
            [
                'profession' => 'Gambler',
                'title' => 'Lucky Streak',
                'description' => 'You go on a lucky winning streak.',
                'image' => '/css/images/profession/gambler.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Keep playing', 'stat_effects' => '+15 Wealth, +10 Luck', 'days_to_advance' => 0],
                    ['text' => 'Cash out', 'stat_effects' => '+20 Wealth, +5 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Gambler'],
            ],
            [
                'profession' => 'Gambler',
                'title' => 'Losing Streak',
                'description' => 'You go on a losing streak.',
                'image' => '/css/images/profession/gambler.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Chase losses', 'stat_effects' => '-25 Wealth, +10 Burnout', 'days_to_advance' => 0],
                    ['text' => 'Stop playing', 'stat_effects' => '-5 Wealth, +10 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Gambler'],
            ],

            // Casino Owner Profession Events
            [
                'profession' => 'Casino Owner',
                'title' => 'High Roller',
                'description' => 'A high roller visits your casino.',
                'image' => '/css/images/profession/casino.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Cater to VIP', 'stat_effects' => '+25 Wealth, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Treat equally', 'stat_effects' => '+10 Reputation, +5 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Casino Owner'],
            ],
            [
                'profession' => 'Casino Owner',
                'title' => 'Gambling Ring',
                'description' => 'An illegal gambling ring operates in your casino.',
                'image' => '/css/images/profession/casino.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Allow it', 'stat_effects' => '+20 Wealth, -15 Morality', 'days_to_advance' => 0],
                    ['text' => 'Shut it down', 'stat_effects' => '-10 Wealth, +15 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Casino Owner'],
            ],
            [
                'profession' => 'Casino Owner',
                'title' => 'Casino Expansion',
                'description' => 'You consider expanding your casino.',
                'image' => '/css/images/profession/casino.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Expand', 'stat_effects' => '+25 Wealth, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Stay same', 'stat_effects' => '+5 Wealth, +5 Happiness', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Casino Owner'],
            ],

            // Priest/Religious Leader Profession Events
            [
                'profession' => 'Priest/Religious Leader',
                'title' => 'Service',
                'description' => 'You lead a religious service.',
                'image' => '/css/images/profession/priest.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Inspire congregation', 'stat_effects' => '+20 Morality, +15 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Basic service', 'stat_effects' => '+5 Morality, +3 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Priest/Religious Leader'],
            ],
            [
                'profession' => 'Priest/Religious Leader',
                'title' => 'Faith Crisis',
                'description' => 'You face a faith crisis.',
                'image' => '/css/images/profession/priest.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Find answers', 'stat_effects' => '+15 Morality, +10 Intelligence', 'days_to_advance' => 0],
                    ['text' => 'Doubt', 'stat_effects' => '-10 Morality, +5 Isolation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Priest/Religious Leader'],
            ],
            [
                'profession' => 'Priest/Religious Leader',
                'title' => 'Community Outreach',
                'description' => 'You reach out to the community.',
                'image' => '/css/images/profession/priest.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Help others', 'stat_effects' => '+15 Morality, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Focus internally', 'stat_effects' => '+5 Morality, +5 Isolation', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Priest/Religious Leader'],
            ],

            // Entrepreneur Profession Events
            [
                'profession' => 'Entrepreneur',
                'title' => 'Startup Launch',
                'description' => 'You launch a new startup.',
                'image' => '/css/images/profession/entrepreneur.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Launch startup', 'stat_effects' => '+15 Wealth, +10 Creativity', 'days_to_advance' => 0],
                    ['text' => 'Delay launch', 'stat_effects' => '-5 Wealth, +5 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Entrepreneur'],
            ],
            [
                'profession' => 'Entrepreneur',
                'title' => 'Funding Round',
                'description' => 'Investors want to fund your startup.',
                'image' => '/css/images/profession/entrepreneur.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Accept funding', 'stat_effects' => '+20 Wealth, +10 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Stay bootstrapped', 'stat_effects' => '+10 Creativity, +5 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Entrepreneur'],
            ],
            [
                'profession' => 'Entrepreneur',
                'title' => 'Pivot',
                'description' => 'Your startup needs to pivot.',
                'image' => '/css/images/profession/entrepreneur.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Pivot business', 'stat_effects' => '+15 Creativity, +10 Discipline', 'days_to_advance' => 0],
                    ['text' => 'Stick to plan', 'stat_effects' => '-10 Wealth, +5 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Entrepreneur'],
            ],

            // Musician Profession Events
            [
                'profession' => 'Musician',
                'title' => 'Concert',
                'description' => 'You perform at a major concert.',
                'image' => '/css/images/profession/musician.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Great performance', 'stat_effects' => '+20 Reputation, +15 Happiness', 'days_to_advance' => 0],
                    ['text' => 'Mediocre performance', 'stat_effects' => '+5 Reputation, -5 Happiness', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Musician'],
            ],
            [
                'profession' => 'Musician',
                'title' => 'Record Deal',
                'description' => 'A record label offers you a deal.',
                'image' => '/css/images/profession/musician.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Sign deal', 'stat_effects' => '+20 Wealth, +15 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Stay independent', 'stat_effects' => '+10 Creativity, +5 Happiness', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Musician'],
            ],
            [
                'profession' => 'Musician',
                'title' => 'Writer\'s Block',
                'description' => 'You struggle to write new music.',
                'image' => '/css/images/profession/musician.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Find inspiration', 'stat_effects' => '+15 Creativity, +5 Discipline', 'days_to_advance' => 0],
                    ['text' => 'Take break', 'stat_effects' => '+10 Happiness, -5 Creativity', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Musician'],
            ],

            // Farmer Profession Events
            [
                'profession' => 'Farmer',
                'title' => 'Harvest Season',
                'description' => 'It is time for the harvest.',
                'image' => '/css/images/profession/farmer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Good harvest', 'stat_effects' => '+15 Wealth, +10 Happiness', 'days_to_advance' => 0],
                    ['text' => 'Bad harvest', 'stat_effects' => '-10 Wealth, +5 Burnout', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Farmer'],
            ],
            [
                'profession' => 'Farmer',
                'title' => 'Pest Infestation',
                'description' => 'Pests are destroying your crops.',
                'image' => '/css/images/profession/farmer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Use pesticides', 'stat_effects' => '-5 Wealth, +10 Health', 'days_to_advance' => 0],
                    ['text' => 'Go organic', 'stat_effects' => '-15 Wealth, +10 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Farmer'],
            ],
            [
                'profession' => 'Farmer',
                'title' => 'Farm Expansion',
                'description' => 'You have an opportunity to expand your farm.',
                'image' => '/css/images/profession/farmer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Expand farm', 'stat_effects' => '+20 Wealth, +5 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Stay small', 'stat_effects' => '+5 Happiness, +3 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Farmer'],
            ],

            // Lawyer Profession Events
            [
                'profession' => 'Lawyer',
                'title' => 'Court Victory',
                'description' => 'You win a major court case!',
                'image' => '/css/images/profession/lawyer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 3,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 1,
                'choices' => [
                    ['text' => 'Celebrate victory', 'stat_effects' => '+15 Reputation, +10 Wealth', 'days_to_advance' => 0],
                    ['text' => 'Stay professional', 'stat_effects' => '+5 Reputation, +3 Wealth', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Lawyer'],
            ],
            [
                'profession' => 'Lawyer',
                'title' => 'Court Loss',
                'description' => 'You lose an important court case.',
                'image' => '/css/images/profession/lawyer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 2,
                'choices' => [
                    ['text' => 'Accept defeat', 'stat_effects' => '-10 Reputation, -5 Happiness', 'days_to_advance' => 0],
                    ['text' => 'Appeal', 'stat_effects' => '-5 Wealth, +3 Discipline', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Lawyer'],
            ],
            [
                'profession' => 'Lawyer',
                'title' => 'Pro Bono Case',
                'description' => 'You take on a pro bono case for a good cause.',
                'image' => '/css/images/profession/lawyer.png',
                'type' => 'profession',
                'deck_label' => 'Profession Event',
                'repeatable' => true,
                'weight' => 2,
                'auto_resolve' => false,
                'days_to_advance' => 0,
                'display_order' => 3,
                'choices' => [
                    ['text' => 'Take the case', 'stat_effects' => '+10 Morality, +5 Reputation', 'days_to_advance' => 0],
                    ['text' => 'Decline', 'stat_effects' => '+3 Wealth, -3 Morality', 'days_to_advance' => 0],
                ],
                'conditions' => ['profession' => 'Lawyer'],
            ],
        ];

        foreach ($events as $event) {
            // Use title as event_choice if not specified
            if (!isset($event['event_choice']) && isset($event['title'])) {
                $event['event_choice'] = $event['title'];
            }
            // Provide default outcome if not set
            if (!isset($event['outcome'])) {
                $event['outcome'] = $event['description'] ?? 'Profession event experienced.';
            }
            // Provide default stat_effects if not set
            if (!isset($event['stat_effects'])) {
                $event['stat_effects'] = '+5 Reputation';
            }
            ProfessionPathEvent::firstOrCreate(
                ['profession' => $event['profession'], 'title' => $event['title']],
                $event
            );
        }

        // Ensure all profession path events have choices
        $this->ensureProfessionPathChoices();
    }

    private function ensureProfessionPathChoices(): void
    {
        $events = ProfessionPathEvent::all();
        foreach ($events as $event) {
            if ($this->eventHasChoices($event->choices ?? null)) {
                continue;
            }
            // Add default structure for events without choices
            if (!isset($event->type)) {
                $event->type = 'profession';
                $event->deck_label = 'Profession Event';
                $event->repeatable = true;
                $event->auto_resolve = false;
                $event->days_to_advance = 0;
                $event->image = '/css/images/profession/doctor.png';
                $event->conditions = null;
            }
            $eventName = (string) ($event->event_choice ?? $event->title ?? 'Profession Event');
            $choices = $this->generateChoices($eventName, $event->stat_effects ?? null, 'adult', 'profession');
            $event->choices = json_encode($choices);
            $event->save();
        }
    }
}
