<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SampleDecisionLog;

class SampleDecisionLogSeeder extends Seeder
{
    /**
     * Run the database seeders.
     * 
     * Seeds sample decision logs representing different career paths and life decisions
     * across various MBTI types and age groups.
     */
    public function run(): void
    {
        $samples = $this->getSampleData();
        
        foreach ($samples as $sample) {
            SampleDecisionLog::create($sample);
        }
        
        $this->command->info('Sample decision logs seeded successfully!');
        $this->command->info('Total records: ' . count($samples));
    }

    /**
     * Get sample decision log data
     */
    private function getSampleData(): array
    {
        return [
            // ===== TEEN AGE GROUP - Career Exploration =====
            [
                'anon_character_id' => 'sample_teen_001',
                'character_name' => 'Alex Explorer',
                'day' => 3650, // Age 10
                'age_group' => 'teen',
                'profession' => 'student',
                'event_type' => 'daily',
                'event_id' => 1,
                'event_title' => 'Career Fair at School',
                'choice_index' => 2,
                'choice_text' => 'Spend time at the technology booth learning about programming',
                'outcome' => 'Alex discovered a passion for technology and decides to take computer classes.',
                'effects' => json_encode([
                    'intelligence' => 5,
                    'career_interest' => 'technology'
                ]),
                'mbti' => 'INTJ',
                'before_health' => 100,
                'before_happiness' => 85,
                'before_finance' => 100,
                'before_relationship_status' => 'single',
                'before_career_level' => 'student',
                'before_profession' => 'student',
                'after_health' => 100,
                'after_happiness' => 90,
                'after_finance' => 100,
                'after_relationship_status' => 'single',
                'after_career_level' => 'student',
                'after_profession' => 'student',
                'health_change' => 0,
                'happiness_change' => 5,
                'finance_change' => 0,
                'tags' => json_encode(['career', 'education', 'technology']),
                'is_featured' => true,
                'view_count' => 0,
            ],
            [
                'anon_character_id' => 'sample_teen_002',
                'character_name' => 'Jordan Creative',
                'day' => 4015, // Age 11
                'age_group' => 'teen',
                'profession' => 'student',
                'event_type' => 'cultural',
                'event_id' => 10,
                'event_title' => 'Art Festival Opportunity',
                'choice_index' => 1,
                'choice_text' => 'Enter the young artists competition with a portrait',
                'outcome' => 'Jordan won first place and discovered artistic talent.',
                'effects' => json_encode([
                    'creativity' => 10,
                    'confidence' => 5
                ]),
                'mbti' => 'INFP',
                'before_health' => 95,
                'before_happiness' => 80,
                'before_finance' => 200,
                'before_relationship_status' => 'single',
                'before_career_level' => 'student',
                'before_profession' => 'student',
                'after_health' => 95,
                'after_happiness' => 95,
                'after_finance' => 300,
                'after_relationship_status' => 'single',
                'after_career_level' => 'student',
                'after_profession' => 'student',
                'health_change' => 0,
                'happiness_change' => 15,
                'finance_change' => 100,
                'tags' => json_encode(['creativity', 'art', 'hobby']),
                'is_featured' => true,
                'view_count' => 0,
            ],

            // ===== YOUNG ADULT - Career Building =====
            [
                'anon_character_id' => 'sample_young_001',
                'character_name' => 'Taylor Career',
                'day' => 7300, // Age 20
                'age_group' => 'young_adult',
                'profession' => 'software_engineer',
                'event_type' => 'profession',
                'event_id' => 100,
                'event_title' => 'First Major Project Deadline',
                'choice_index' => 0,
                'choice_text' => 'Work overtime to ensure the project is perfect',
                'outcome' => 'Project was successful but Taylor felt exhausted.',
                'effects' => json_encode([
                    'career_progress' => 15,
                    'burnout_risk' => 10
                ]),
                'mbti' => 'ISTJ',
                'before_health' => 95,
                'before_happiness' => 80,
                'before_finance' => 5000,
                'before_relationship_status' => 'dating',
                'before_career_level' => 'entry',
                'before_profession' => 'junior_developer',
                'after_health' => 85,
                'after_happiness' => 75,
                'after_finance' => 8000,
                'after_relationship_status' => 'dating',
                'after_career_level' => 'junior',
                'after_profession' => 'software_engineer',
                'health_change' => -10,
                'happiness_change' => -5,
                'finance_change' => 3000,
                'tags' => json_encode(['career', 'work-life-balance', 'ambition']),
                'is_featured' => true,
                'view_count' => 0,
            ],
            [
                'anon_character_id' => 'sample_young_002',
                'character_name' => 'Casey Social',
                'day' => 7675, // Age 21
                'age_group' => 'young_adult',
                'profession' => 'marketing_specialist',
                'event_type' => 'daily',
                'event_id' => 50,
                'event_title' => 'Office Team Building Event',
                'choice_index' => 1,
                'choice_text' => 'Organize a team activity and volunteer to lead',
                'outcome' => 'Colleagues appreciated the initiative, building stronger work relationships.',
                'effects' => json_encode([
                    'social_skills' => 10,
                    'reputation' => 5,
                    'charisma' => 5
                ]),
                'mbti' => 'ENFJ',
                'before_health' => 90,
                'before_happiness' => 75,
                'before_finance' => 3000,
                'before_relationship_status' => 'single',
                'before_career_level' => 'entry',
                'before_profession' => 'marketing_coordinator',
                'after_health' => 90,
                'after_happiness' => 85,
                'after_finance' => 3500,
                'after_relationship_status' => 'dating',
                'after_career_level' => 'entry',
                'after_profession' => 'marketing_specialist',
                'health_change' => 0,
                'happiness_change' => 10,
                'finance_change' => 500,
                'tags' => json_encode(['networking', 'leadership', 'social']),
                'is_featured' => false,
                'view_count' => 0,
            ],
            [
                'anon_character_id' => 'sample_young_003',
                'character_name' => 'Morgan Tech',
                'day' => 8400, // Age 23
                'age_group' => 'young_adult',
                'profession' => 'data_scientist',
                'event_type' => 'profession',
                'event_id' => 120,
                'event_title' => 'Graduate School Opportunity',
                'choice_index' => 0,
                'choice_text' => 'Accept the offer for a data science master\'s program',
                'outcome' => 'Morgan gained advanced skills but took on student loans.',
                'effects' => json_encode([
                    'intelligence' => 15,
                    'future_earning_potential' => 20,
                    'debt' => -30000
                ]),
                'mbti' => 'INTP',
                'before_health' => 100,
                'before_happiness' => 85,
                'before_finance' => 10000,
                'before_relationship_status' => 'single',
                'before_career_level' => 'junior',
                'before_profession' => 'data_analyst',
                'after_health' => 95,
                'after_happiness' => 80,
                'after_finance' => -20000,
                'after_relationship_status' => 'single',
                'after_career_level' => 'junior',
                'after_profession' => 'data_scientist',
                'health_change' => -5,
                'happiness_change' => -5,
                'finance_change' => -30000,
                'tags' => json_encode(['education', 'career', 'investment']),
                'is_featured' => true,
                'view_count' => 0,
            ],

            // ===== ADULT - Career Advancement =====
            [
                'anon_character_id' => 'sample_adult_001',
                'character_name' => 'Riley Executive',
                'day' => 10950, // Age 30
                'age_group' => 'adult',
                'profession' => 'product_manager',
                'event_type' => 'profession',
                'event_id' => 150,
                'event_title' => 'Promotion to Management',
                'choice_index' => 1,
                'choice_text' => 'Accept the promotion to team lead',
                'outcome' => 'Riley now manages a team of 8 people with higher salary.',
                'effects' => json_encode([
                    'career_level' => 'manager',
                    'income' => 20000,
                    'responsibility' => 15
                ]),
                'mbti' => 'ENTJ',
                'before_health' => 90,
                'before_happiness' => 80,
                'before_finance' => 50000,
                'before_relationship_status' => 'engaged',
                'before_career_level' => 'senior',
                'before_profession' => 'senior_developer',
                'after_health' => 85,
                'after_happiness' => 85,
                'after_finance' => 70000,
                'after_relationship_status' => 'engaged',
                'after_career_level' => 'manager',
                'after_profession' => 'product_manager',
                'health_change' => -5,
                'happiness_change' => 5,
                'finance_change' => 20000,
                'tags' => json_encode(['career', 'leadership', 'promotion']),
                'is_featured' => true,
                'view_count' => 0,
            ],
            [
                'anon_character_id' => 'sample_adult_002',
                'character_name' => 'Quinn Family',
                'day' => 11680, // Age 32
                'age_group' => 'adult',
                'profession' => 'nurse',
                'event_type' => 'daily',
                'event_id' => 80,
                'event_title' => 'Work-Life Balance Decision',
                'choice_index' => 2,
                'choice_text' => 'Reduce hours to part-time to spend more time with family',
                'outcome' => 'Quinn has more family time but reduced income.',
                'effects' => json_encode([
                    'family_bonding' => 15,
                    'income_reduction' => -15000,
                    'stress' => -10
                ]),
                'mbti' => 'ISFJ',
                'before_health' => 85,
                'before_happiness' => 70,
                'before_finance' => 45000,
                'before_relationship_status' => 'married',
                'before_career_level' => 'senior',
                'before_profession' => 'nurse',
                'after_health' => 90,
                'after_happiness' => 85,
                'after_finance' => 30000,
                'after_relationship_status' => 'married',
                'after_career_level' => 'entry',
                'after_profession' => 'nurse',
                'health_change' => 5,
                'happiness_change' => 15,
                'finance_change' => -15000,
                'tags' => json_encode(['family', 'work-life-balance', 'health']),
                'is_featured' => true,
                'view_count' => 0,
            ],
            [
                'anon_character_id' => 'sample_adult_003',
                'character_name' => 'Avery Entrepreneur',
                'day' => 12775, // Age 35
                'age_group' => 'adult',
                'profession' => 'startup_founder',
                'event_type' => 'profession',
                'event_id' => 200,
                'event_title' => 'Startup Opportunity',
                'choice_index' => 0,
                'choice_text' => 'Quit job to launch own tech startup',
                'outcome' => 'High risk, high reward decision with uncertain future.',
                'effects' => json_encode([
                    'entrepreneurship' => 20,
                    'risk' => 'high',
                    'potential_return' => 'very_high'
                ]),
                'mbti' => 'ENTP',
                'before_health' => 95,
                'before_happiness' => 85,
                'before_finance' => 100000,
                'before_relationship_status' => 'dating',
                'before_career_level' => 'manager',
                'before_profession' => 'software_architect',
                'after_health' => 80,
                'after_happiness' => 90,
                'after_finance' => 50000,
                'after_relationship_status' => 'engaged',
                'after_career_level' => 'executive',
                'after_profession' => 'startup_founder',
                'health_change' => -15,
                'happiness_change' => 5,
                'finance_change' => -50000,
                'tags' => json_encode(['entrepreneurship', 'risk', 'career']),
                'is_featured' => true,
                'view_count' => 0,
            ],

            // ===== MIDDLE AGED - Career Peak / Transition =====
            [
                'anon_character_id' => 'sample_middle_001',
                'character_name' => 'Drew Mentor',
                'day' => 16425, // Age 45
                'age_group' => 'middle_aged',
                'profession' => 'engineering_manager',
                'event_type' => 'profession',
                'event_id' => 250,
                'event_title' => 'Mentoring Opportunity',
                'choice_index' => 1,
                'choice_text' => 'Take on a junior developer as mentor',
                'outcome' => 'Drew found purpose in teaching and developed leadership skills.',
                'effects' => json_encode([
                    'leadership' => 10,
                    'satisfaction' => 15,
                    'wisdom' => 5
                ]),
                'mbti' => 'INFJ',
                'before_health' => 80,
                'before_happiness' => 75,
                'before_finance' => 200000,
                'before_relationship_status' => 'married',
                'before_career_level' => 'senior_manager',
                'before_profession' => 'engineering_manager',
                'after_health' => 80,
                'after_happiness' => 90,
                'after_finance' => 210000,
                'after_relationship_status' => 'married',
                'after_career_level' => 'senior_manager',
                'after_profession' => 'engineering_manager',
                'health_change' => 0,
                'happiness_change' => 15,
                'finance_change' => 10000,
                'tags' => json_encode(['mentoring', 'leadership', 'personal-growth']),
                'is_featured' => true,
                'view_count' => 0,
            ],
            [
                'anon_character_id' => 'sample_middle_002',
                'character_name' => 'Skyler CareerChange',
                'day' => 18250, // Age 50
                'age_group' => 'middle_aged',
                'profession' => 'career_coach',
                'event_type' => 'profession',
                'event_id' => 300,
                'event_title' => 'Mid-Life Career Change',
                'choice_index' => 0,
                'choice_text' => 'Leave corporate job to become a career coach',
                'outcome' => 'Skyler found new purpose helping others but took a pay cut.',
                'effects' => json_encode([
                    'career_change' => 'significant',
                    'satisfaction' => 20,
                    'income_change' => -30000
                ]),
                'mbti' => 'ESFJ',
                'before_health' => 75,
                'before_happiness' => 60,
                'before_finance' => 350000,
                'before_relationship_status' => 'married',
                'before_career_level' => 'executive',
                'before_profession' => 'vice_president',
                'after_health' => 80,
                'after_happiness' => 85,
                'after_finance' => 320000,
                'after_relationship_status' => 'married',
                'after_career_level' => 'senior',
                'after_profession' => 'career_coach',
                'health_change' => 5,
                'happiness_change' => 25,
                'finance_change' => -30000,
                'tags' => json_encode(['career-change', 'personal-growth', 'helping-others']),
                'is_featured' => true,
                'view_count' => 0,
            ],

            // ===== SENIOR - Retirement Planning =====
            [
                'anon_character_id' => 'sample_senior_001',
                'character_name' => 'Jordan Retiree',
                'day' => 25550, // Age 70
                'age_group' => 'senior',
                'profession' => 'retired_consultant',
                'event_type' => 'daily',
                'event_id' => 400,
                'event_title' => 'Retirement Decision',
                'choice_index' => 1,
                'choice_text' => 'Fully retire and enjoy hobbies',
                'outcome' => 'Jordan enjoys peaceful retirement with gardening and reading.',
                'effects' => json_encode([
                    'retirement' => true,
                    'stress' => -20,
                    'leisure_time' => 'abundant'
                ]),
                'mbti' => 'ISTP',
                'before_health' => 70,
                'before_happiness' => 75,
                'before_finance' => 500000,
                'before_relationship_status' => 'married',
                'before_career_level' => 'retired',
                'before_profession' => 'consultant',
                'after_health' => 75,
                'after_happiness' => 90,
                'after_finance' => 480000,
                'after_relationship_status' => 'married',
                'after_career_level' => 'retired',
                'after_profession' => 'retired',
                'health_change' => 5,
                'happiness_change' => 15,
                'finance_change' => -20000,
                'tags' => json_encode(['retirement', 'leisure', 'health']),
                'is_featured' => true,
                'view_count' => 0,
            ],
            [
                'anon_character_id' => 'sample_senior_002',
                'character_name' => 'Casey Legacy',
                'day' => 27000, // Age 74
                'age_group' => 'senior',
                'profession' => 'retired_professor',
                'event_type' => 'cultural',
                'event_id' => 450,
                'event_title' => 'Legacy Building',
                'choice_index' => 0,
                'choice_text' => 'Write a book about career experiences',
                'outcome' => 'Casey\'s book became popular among young professionals.',
                'effects' => json_encode([
                    'legacy' => true,
                    'influence' => 15,
                    'wisdom_sharing' => 20
                ]),
                'mbti' => 'INTJ',
                'before_health' => 65,
                'before_happiness' => 80,
                'before_finance' => 600000,
                'before_relationship_status' => 'widowed',
                'before_career_level' => 'retired',
                'before_profession' => 'professor',
                'after_health' => 65,
                'after_happiness' => 90,
                'after_finance' => 620000,
                'after_relationship_status' => 'widowed',
                'after_career_level' => 'retired',
                'after_profession' => 'retired_professor',
                'health_change' => 0,
                'happiness_change' => 10,
                'finance_change' => 20000,
                'tags' => json_encode(['legacy', 'wisdom', 'writing']),
                'is_featured' => false,
                'view_count' => 0,
            ],

            // ===== DIVERSE MBTI EXAMPLES =====
            // ESFP - The Performer
            [
                'anon_character_id' => 'sample_esfp_001',
                'character_name' => 'Sam Performer',
                'day' => 8035, // Age 22
                'age_group' => 'young_adult',
                'profession' => 'event_planner',
                'event_type' => 'daily',
                'event_id' => 60,
                'event_title' => 'Exciting Opportunity',
                'choice_index' => 0,
                'choice_text' => 'Accept job offer for a prestigious event planning company',
                'outcome' => 'Sam thrives in the dynamic, people-focused environment.',
                'effects' => json_encode([
                    'social' => 15,
                    'creativity' => 10,
                    'energy' => 'high'
                ]),
                'mbti' => 'ESFP',
                'before_health' => 100,
                'before_happiness' => 85,
                'before_finance' => 2000,
                'before_relationship_status' => 'single',
                'before_career_level' => 'student',
                'before_profession' => 'student',
                'after_health' => 95,
                'after_happiness' => 95,
                'after_finance' => 6000,
                'after_relationship_status' => 'dating',
                'after_career_level' => 'entry',
                'after_profession' => 'event_planner',
                'health_change' => -5,
                'happiness_change' => 10,
                'finance_change' => 4000,
                'tags' => json_encode(['social', 'creativity', 'career']),
                'is_featured' => false,
                'view_count' => 0,
            ],
            // ISFP - The Adventurer
            [
                'anon_character_id' => 'sample_isfp_001',
                'character_name' => 'Jamie Artist',
                'day' => 9490, // Age 26
                'age_group' => 'young_adult',
                'profession' => 'graphic_designer',
                'event_type' => 'profession',
                'event_id' => 140,
                'event_title' => 'Work Abroad Option',
                'choice_index' => 1,
                'choice_text' => 'Take a remote freelance project while traveling Asia',
                'outcome' => 'Jamie gained cultural experiences and unique design inspiration.',
                'effects' => json_encode([
                    'creativity' => 15,
                    'cultural_exposure' => 20,
                    'adventure' => true
                ]),
                'mbti' => 'ISFP',
                'before_health' => 95,
                'before_happiness' => 80,
                'before_finance' => 25000,
                'before_relationship_status' => 'single',
                'before_career_level' => 'junior',
                'before_profession' => 'graphic_designer',
                'after_health' => 90,
                'after_happiness' => 95,
                'after_finance' => 20000,
                'after_relationship_status' => 'single',
                'after_career_level' => 'junior',
                'after_profession' => 'graphic_designer',
                'health_change' => -5,
                'happiness_change' => 15,
                'finance_change' => -5000,
                'tags' => json_encode(['travel', 'creativity', 'lifestyle']),
                'is_featured' => false,
                'view_count' => 0,
            ],
            // ESTJ - The Executive
            [
                'anon_character_id' => 'sample_estj_001',
                'character_name' => 'Taylor Manager',
                'day' => 10500, // Age 28.5
                'age_group' => 'young_adult',
                'profession' => 'operations_manager',
                'event_type' => 'profession',
                'event_id' => 145,
                'event_title' => 'Company Restructuring',
                'choice_index' => 0,
                'choice_text' => 'Lead the department through difficult restructuring',
                'outcome' => 'Taylor successfully navigated the crisis and earned promotion.',
                'effects' => json_encode([
                    'leadership' => 15,
                    'reputation' => 20,
                    'stress' => 15
                ]),
                'mbti' => 'ESTJ',
                'before_health' => 90,
                'before_happiness' => 80,
                'before_finance' => 60000,
                'before_relationship_status' => 'engaged',
                'before_career_level' => 'senior',
                'before_profession' => 'operations_specialist',
                'after_health' => 80,
                'after_happiness' => 85,
                'after_finance' => 90000,
                'after_relationship_status' => 'married',
                'after_career_level' => 'manager',
                'after_profession' => 'operations_manager',
                'health_change' => -10,
                'happiness_change' => 5,
                'finance_change' => 30000,
                'tags' => json_encode(['leadership', 'challenge', 'career']),
                'is_featured' => false,
                'view_count' => 0,
            ],
        ];
    }
}
